package webapi

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"google.golang.org/genai"
)

// GeminiService handles interactions with the Google Gemini API.
type GeminiService struct {
	client *genai.Client
}

// NewGeminiService creates a new GeminiService.
func NewGeminiService(ctx context.Context) (*GeminiService, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return nil, fmt.Errorf("la variable de entorno GEMINI_API_KEY no está configurada")
	}

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey: apiKey,
	})
	if err != nil {
		return nil, fmt.Errorf("error al crear el cliente de Gemini: %w", err)
	}

	return &GeminiService{client: client}, nil
}

// TransactionInfo holds the structured data extracted from an SMS.
type TransactionInfo struct {
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
	Merchant    string  `json:"merchant"`
	Date        string  `json:"date"` // Format YYYY-MM-DD
}

// PatternGenerationResult holds the regex patterns generated by the AI.
type PatternGenerationResult struct {
	AmountRegex      string   `json:"amount_regex"`
	DateRegex        string   `json:"date_regex"`
	DescriptionRegex string   `json:"description_regex"`
	MerchantRegex    string   `json:"merchant_regex"`
	KeywordsTrigger  []string `json:"keywords_trigger"`
}

// ExtractTransactionInfoFromSMS analyzes an SMS and extracts transaction details.
func (s *GeminiService) ExtractTransactionInfoFromSMS(ctx context.Context, smsContent string) (*TransactionInfo, error) {
	prompt := genai.Text(fmt.Sprintf(`
        Analiza el siguiente SMS de una notificación bancaria y extrae la información en formato JSON.
        El SMS es: "%s"

        El JSON de salida debe tener la siguiente estructura y tipos de datos:
        {
            "amount": float64,      // El monto de la transacción.
            "description": "string", // Una descripción corta y limpia de la compra.
            "merchant": "string",    // El nombre del comercio.
            "date": "string"         // La fecha en formato YYYY-MM-DD. Si no hay fecha, usa la fecha actual.
        }

        Ejemplo de salida:
        {
            "amount": 150.00,
            "description": "Compra en OXXO",
            "merchant": "OXXO",
            "date": "2024-01-15"
        }
    `, smsContent))

	config := &genai.GenerateContentConfig{
		Temperature:      genai.Ptr[float32](0.0),
		ResponseMIMEType: "application/json",
	}

	resp, err := s.client.Models.GenerateContent(ctx, "gemini-1.5-flash", prompt, config)
	if err != nil {
		return nil, fmt.Errorf("error al generar contenido con Gemini: %w", err)
	}

	if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("la respuesta de Gemini está vacía o mal formada")
	}

	jsonStr := resp.Text()
	if jsonStr == "" {
		return nil, fmt.Errorf("el contenido de la respuesta de Gemini está vacío")
	}

	jsonStr = strings.TrimSpace(jsonStr)
	jsonStr = strings.TrimPrefix(jsonStr, "```json")
	jsonStr = strings.TrimSuffix(jsonStr, "```")
	jsonStr = strings.TrimSpace(jsonStr)

	var info TransactionInfo
	if err := json.Unmarshal([]byte(jsonStr), &info); err != nil {
		return nil, fmt.Errorf("error al decodificar el JSON de Gemini: %w (JSON recibido: %s)", err, jsonStr)
	}

	return &info, nil
}

// GeneratePatternFromMessage analyzes a message and generates regex patterns.
func (s *GeminiService) GeneratePatternFromMessage(ctx context.Context, messageContent string) (*PatternGenerationResult, error) {
	prompt := genai.Text(fmt.Sprintf(`
		Tu tarea es actuar como un experto en expresiones regulares (regex) para analizar un mensaje de notificación bancaria y generar un patrón para futuras notificaciones.

		Analiza el siguiente mensaje:
		"%s"

		Basado en el mensaje, genera un objeto JSON con las siguientes claves:
		- "amount_regex": Una expresión regular para extraer el monto. Debe capturar el valor numérico (con decimales, sin símbolos de moneda). Ejemplo: para '$1,500.50' el regex debe capturar '1,500.50'.
		- "date_regex": Una expresión regular para extraer la fecha completa si existe (ej: "dd/MM/yyyy" o "dd de Enero"). Si no hay fecha, debe ser un string vacío "".
		- "description_regex": Una expresión regular para extraer la descripción de la transacción (ej: "Compra en", "Transferencia a"). Debe ser concisa.
		- "merchant_regex": Una expresión regular para extraer el nombre del comercio o destinatario.
		- "keywords_trigger": Una lista de 1 a 3 palabras clave importantes que siempre aparecerán en este tipo de mensaje (ej: ["Compra", "BBVA", "Transferencia"]).

		Ejemplo de salida para el mensaje "BBVA: Compra por $1,500.50 en OXXO el 15/01/2024":
		{
			"amount_regex": "([\\d,]+\\.\\d{2})",
			"date_regex": "(\\d{2}/\\d{2}/\\d{4})",
			"description_regex": "(Compra por)",
			"merchant_regex": "en ([\\w\\s]+) el",
			"keywords_trigger": ["BBVA", "Compra", "OXXO"]
		}

		Asegúrate de que el JSON sea válido y de que las expresiones regulares estén correctamente escapadas para su uso en JSON. La respuesta debe ser únicamente el objeto JSON.
	`, messageContent))

	config := &genai.GenerateContentConfig{
		Temperature:      genai.Ptr[float32](0.0),
		ResponseMIMEType: "application/json",
	}

	resp, err := s.client.Models.GenerateContent(ctx, "gemini-1.5-flash", prompt, config)
	if err != nil {
		return nil, fmt.Errorf("error al generar patrón con Gemini: %w", err)
	}

	if len(resp.Candidates) == 0 || resp.Candidates[0].Content == nil || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("la respuesta de Gemini para generar patrón está vacía o mal formada")
	}

	jsonStr := resp.Text()
	if jsonStr == "" {
		return nil, fmt.Errorf("el contenido de la respuesta de Gemini para generar patrón está vacío")
	}

	jsonStr = strings.TrimSpace(jsonStr)
	jsonStr = strings.TrimPrefix(jsonStr, "```json")
	jsonStr = strings.TrimSuffix(jsonStr, "```")
	jsonStr = strings.TrimSpace(jsonStr)

	var result PatternGenerationResult
	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		return nil, fmt.Errorf("error al decodificar el JSON de Gemini para el patrón: %w (JSON recibido: %s)", err, jsonStr)
	}

	return &result, nil
}
